language: python
python:
    - "3.6"
before_script: cd workingTimeManagerBase

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python manage.py test

env:
  - DJANGO_VERSION=2.0.1
