language: python
python:
    - "3.6"

before_install:
  - sudo mysql -e "use mysql; CREATE USER 'worker'@'localhost' IDENTIFIED BY 'workerpassword'; grant all privileges on *.* to 'worker'@'localhost';FLUSH PRIVILEGES;"
  - sudo service mysql restart

# command to install dependencies
install:
  - pip install -r workingTimeManagerBase/requirements.txt

before_script:
  - cd workingTimeManagerBase
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
# command to run tests
script:
  - coverage run manage.py test
  - coverage xml

after_script:
  - ./cc-test-reporter after-build -t coverage.py --debug --exit-code $TRAVIS_TEST_RESULT

services:
  - mysql

env:
  global:
    CC_TEST_REPORTER_ID=b14fc3b328c8647741951f3e25ef0c696d340b9740408e73e01aae1d338a39e8
