language: python
python:
    - "3.6"

before_install:
  - sudo mysql -e "use mysql; CREATE USER 'worker'@'localhost' IDENTIFIED BY 'workerpassword'; ALTER USER worker CREATEDB; GRANT ALL PRIVILEGES ON workingtimedb.* TO 'worker'@'localhost';FLUSH PRIVILEGES;"
  - sudo service mysql restart

# command to install dependencies
install:
  - pip install -r workingTimeManagerBase/requirements.txt

before_script:
  - cd workingTimeManagerBase

# command to run tests
script:
  - python manage.py test

env:
  - DJANGO_VERSION=2.0.8

services:
  - mysql
