language: python
python:
    - "3.6"

before_install:
  - sudo mysql_upgrade --force -u root --password=travis -h 127.0.0.1
  - sudo mysql -e "use mysql; CREATE USER 'worker'@'localhost' IDENTIFIED BY 'workerpassword';FLUSH PRIVILEGES;"
  - sudo service mysql restart

# command to install dependencies
install:
  - pip install -r workingTimeManagerBase/requirements.txt

before_script:
  - cd workingTimeManagerBase

# command to run tests
script:
  - python manage.py test

env:
  - DJANGO_VERSION=2.0.8

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
