language: python
python:
    - "3.6"

before_install:
  - sudo mysql -e "use mysql; CREATE USER 'worker'@'localhost' IDENTIFIED BY 'workerpassword'; grant all privileges on *.* to 'worker'@'localhost';FLUSH PRIVILEGES;"
  - sudo service mysql restart

# command to install dependencies
install:
  - pip install -r workingTimeManagerBase/requirements.txt

before_script:
  - cd workingTimeManagerBase

# command to run tests
script:
  - python manage.py test
  - coverage html

after_script:
  - codeclimate-test-reporter --file .coverage

env:
  - DJANGO_VERSION=2.0.8

services:
  - mysql

addons:
  code_climate:
    repo_token:
      secure: "pMhdF99mIw0Ur/Gvg6fPq6COiwxGP78TYdDNOMOjxWbYoyOaUlPylp5WEi5/d5Vb/5GJ4zXeTRn5db/9lElv1CC3JL+TVf4KSvaHIeW+FUwuqSo9CFO6AZVuFVsHVqPW+v+Zu4oR7fnfQIk2T8l6yy5X1X+4G8XyukCmIpULN7fN37wfDyQdRMyFwhDxtqmTBdD2pAe7Zs+VTn37EHWfUqYg/wL2VU0ujTZANpk/F7SmmCZjq+3xG5NdJJk2lUGv2o0VFFm1Gn9jivc076+6c/OAVq5g7FqW0r0fKT+teL+iJ12o0s3n9qjvWS2IYvgt1GcSW77nEUJj+BcRKgivL4F1GkGLFvKiLYm3RiE6TFMNwqXabzlQ16JD77awP+snivfjkB1ZjgLZfAFrAHzrBJvVD6Y4ixU8vumQttjnDPgzQNqyZZKpBX8gH7ttshDCUoJg3TkC3VX9gXJKLus+T2GOHwf1BMOydzhUK33M+XFucWsbmeeGhwUlmMSiu7QRrZOkv4C5d0A8OkFY8N7zM7qDQjgZZf8pJQW2qtOFgNUIJCSj7PjxAHoGXfGw3uiFWdtJyCw1fOKIKi33OjjQu/aZhJkzqkLzHV90cr0by8B4Lttprcp8FF6RQzxw9OXAKQt/bH0IfmbUyhFcYN//Y9zI/ShJbcluGdXRJ3XNG74="
